repos:
-   repo: https://github.com/ambv/black
    rev: stable
    hooks:
    - id: black
      language_version: python3.9
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.9
    hooks:
    - id: flake8
-   repo: local
    hooks:
    -   id: pytest
        name: pytest
        entry: coverage run --source=src/ -m pytest test/
        language: python
        'types': [python]
        pass_filenames: false
        stages: [commit]

    -   id: coverage
        name: coverage
        entry: coverage html
        language: python
        'types': [ python ]
        pass_filenames: false
        stages: [commit]
